---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
    - a9fd3c0ba886e05c4747fe08f28d34c7
    - b328d170f8ecde6243e2ca8ee261d32b
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- "**.mock.js"
- "**.spec.js"
