---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 140
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.jsx"
  - "**.module"
exclude_paths:
- "**.mock.js"
- "**.spec.js"
